name: Build, Push and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.3

    - name: Initialize Go module
      run: |
        cd go-app
        if [ ! -f go.mod ]; then
          go mod init go-app
        fi
        go mod tidy

    - name: Log in to Docker Hub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_PSSWD }}     

    - name: Build and push Docker image
      uses: docker/build-push-action@3b5e8027fcad23fda98b2e3ac259d8d67585f671
      with:
        context: ./go-app
        file: ./go-app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/botgauge:v1

         

       
          
          
    