name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.22.3

    - name: Initialize Go module
      run: |
        cd go-app
        if [ ! -f go.mod ]; then
          go mod init go-app
        fi
        go mod tidy

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./go-app
        file: ./go-app/Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/botgauge:v1
      env:
        DOCKER_REGISTRY_USER: ${{ secrets.DOCKER_HUB_USERNAME }}
        DOCKER_REGISTRY_PASS: ${{ secrets.DOCKER_ACCESS_TOKEN }}    
          
    